### ISSUE TITLE
Please update to fpm 0.7.0

### ISSUE THREAD

**Issue by rouson** [fortran-lang/homebrew-fortran#16]
`brew tap fortran-lang/fortran && brew install fpm` still builds `fpm` 0.6.0.  Is there a way to ensure that the latest release will always be used?

**Comment by awvwgk** [comment]
``brew install --HEAD fpm`` should give you the latest fpm version from the git repo. There is already a PR staged for updating #15, but this one seems stale.

**Comment by ivan-pi** [comment]
One more user is affected by this at Fortran Discourse: https://fortran-lang.discourse.group/t/fpm-version-0-7-0-released/4619/5?u=ivanpribec

**Comment by ivan-pi** [comment]
```
$ brew upgrade fpm
Warning: fortran-lang/fortran/fpm 0.6.0_1 already installed
$ brew install --HEAD fpm
Error: No head is defined for fortran-lang/fortran/fpm
```

According to the [Formula Cookbook](https://docs.brew.sh/Formula-Cookbook#unstable-versions-head), we need to add
```
  head do
    url "https://github.com/fortran-lang/fpm.git", branch: "main" # the default is "master"
  end
```
to the recipe.
