### ISSUE TITLE
Issue using Homebrew tap to install fpm

### ISSUE THREAD

**Issue by amaier10** [fortran-lang/homebrew-fortran#32]
When trying to tap the fpm repository, Homebrew keeps asking for GitHub login credentials.
```
brew tap fortran-lang/fpm
==> Tapping fortran-lang/fpm
Cloning into '/opt/homebrew/Library/Taps/fortran-lang/homebrew-fpm'...
Username for 'https://github.com':
```
 I had someone else test the installation instructions and they had no issue, and uninstalling and reinstalling Homebrew doesn't seem to help. Similar issues online seem to suggest that this only happens with private repositories, but the fpm repo is clearly public.This only seems to be an issue with fpm for me.

**Comment by pgierz** [comment]
See #33, maybe that helps your problem?

**Comment by amaier10** [comment]
Yeah, that helps. The tap works without asking for login credentials and I can install fpm.
